### ISSUE TITLE
Add service bug?

### ISSUE THREAD

**Issue by Mjolinir** [opinkerfi/adagios#636] opened 2017-11-16 14:17 UTC
When adding a service, The "Use" option asks you to choose which template to inherit from, but in the dropdown it also shows ALL check commands as well. Shouldn't those be filtered out?

It looks like its: if self.pynag_object.object_type == 'service', but shouldn't it also filter out if the service is "register 1" so only templates are shown, maybe like this? (I did try this and it didn't work):

if self.pynag_object.object_type == 'service' and self.pynag_object['register'] = "0":

For example: Some users are picking "check_http" here because its an option. I dont know python, so forgive me if my syntax is completely wrong :)

**Comment by palli** [comment] 2017-11-16 15:16
Could it be that you have a service out there called "check_http"? I remember seeing this come stock hidden in the template of some nagios default configurations.

I agree filtering on register=0 sounds reasonable, but unfortunately nagios is not always that reasonable. Nagios itself makes no requirement that an object is register=0 in order to be used as a template, instead it allows any object to be a template if it has a name attribute set. In fact from memory I believe many of the default templates shipped with nagios forget to set register=0.

I'll close this bug as "working as intended" for now, but don't hesitate to reopen if you think there is anything that needs fixing on the adagios or pynag side.

**Closed by palli** 2017-11-16 15:16 UTC

**Comment by Mjolinir** [comment] 2017-11-24 17:15
Well, yes, there is a check_http service check, I just used it as an example that ALL service checks are showing along with the templates but they should not be. From the opposite point of view: When you select a service check on the monitoring tab, the templates are not visible (as it should be). Makes sense that the service checks should not be visible when choosing the template.
