### ISSUE TITLE
The requested URL returned error: 404 Not Found : installation issue

### ISSUE THREAD

**Issue by michelebortolotto** [opinkerfi/adagios#530] opened 2015-02-23 15:13 UTC
hi,
I'm trying to install adagios following this guide https://github.com/opinkerfi/adagios/wiki/Install-guide ...but i've this issue

yum update -y ok-release
Loaded plugins: fastestmirror, nethserver_events
Loading mirror speeds from cached hostfile
http://opensource.is/repo/rhel6.5/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: ok. Please verify its path and try again

it seems that opensource.is redirect to https://github.com/opinkerfi where there isn't the "repo/rhel6.5/x86_64/repodata/repomd.xml" path

**Comment by hakong** [comment] 2015-02-26 01:00
I will look into this tomorrow, thanks for reporting!

**Comment by hakong** [comment] 2015-02-26 10:27
@tomas-edwardsson can you help on this?

**Comment by michelebortolotto** [comment] 2015-02-26 10:41
On 02/26/2015 11:27 AM, hakong wrote:
>
> @tomas-edwardsson <https://github.com/tomas-edwardsson> can you help 
> on this?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/opinkerfi/adagios/issues/530#issuecomment-76154940>.
>
this is a workaround" sed -i 's/rhel\$releasever/rhel6/' 
/etc/yum.repos.d/ok.repo "
if it can help for debug

**Comment by hakong** [comment] 2015-02-26 10:52
I'm unable to reproduce this on a stock Centos 6.5 machine.
I followed the install guide and it worked flawlessly.

**Comment by michelebortolotto** [comment] 2015-02-26 13:42
On 02/26/2015 11:52 AM, hakong wrote:
>
> I'm unable to reproduce this on a stock Centos 6.5 machine.
> I followed the install guide and it worked flawlessly.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/opinkerfi/adagios/issues/530#issuecomment-76158310>.
>
ok so probably the problem is in the customizations that nethserver's 
developers (  http://www.nethserver.org/  )have made to Centos, i'll 
report back to them the problem, thanks alot for the feedbacks

**Comment by hakong** [comment] 2015-02-26 14:18
@palli or @tomas-edwardsson or @tryggvi can you close this?

**Closed** 2015-03-14 16:34 UTC
Labels: question
