### ISSUE TITLE
Allow easy clearing of history

### ISSUE THREAD

**Issue by jbondhus** [opinkerfi/adagios#519] opened 2015-01-23 00:35 UTC
After I configured adagios completely on all my hosts, I had a lot of junk filling the logs, details about issues that weren't really there, among other things because in the process of tweaking and configuring things services registered falsely as being down. It would be nice to be able to start with a clean slate state/history wise without removing hosts or my config. That way SLAs would be accurate, issue count per host would be accurate, etc.

**Comment by palli** [comment] 2015-01-25 21:24
Its more of a nagios related thing, than adagios (we only read the log files, its nagios that writes them).

But you can get a clean slate by deleting /var/log/nagios/archives/* (assuming redhat and you install from rpm, might be somewhere else on your system).

**Comment by palli** [comment] 2015-01-25 21:26
Considering that we don't edit log files at all, it does feel like it is 'outside of scope' for adagios to be clearing the history. Marking this as 'working as intended' for now, don't hesitate to reopen if you have questions or concerns.

**Closed by palli** 2015-01-25 21:26 UTC
