### ISSUE TITLE
Adagios access control

### ISSUE THREAD

**Issue by spicysomtam** [opinkerfi/adagios#569] opened 2015-06-23 09:47 UTC
I switched the authentication on adagios and nagios to pwauth, and unix users (who are really AD users) can login. That works fine, however the adagios to nagios authentication breaks; when you click on the nagios link in adagios, and search a host, you then have to authenicate in nagios too (even if using nagiosadmin, which I added as a local linux user).

I updated adagios.conf and nagios.conf to have this authenication:

    AuthName "Nagios Access"
    AuthType Basic
    #   AuthUserFile /etc/nagios/passwd # old setting
    AuthBasicProvider external
    AuthExternal pwauth
    Require valid-user

I also switched on the access control as per the User Guide. Basically you cannot see anything unless you are in the administrator list. I mean you cannot see an overview of host/service status, etc. I kind of thought that non admins would still be able to see adagios status but be blocked from the Configure and Okconfig menus? I think this would be a useful feature; I mean we would need read only access so Ops can monitor but not reconfigure.

**Comment by spicysomtam** [comment] 2015-06-23 15:50
Fixed the nagios integration; I had not updated the cgi section in httpd the nagios.conf.

I restricted access to a particular user group using pwauth, so only users in a particular group can login to adagios or nagios (see this: http://nathanpeters.com/2014/09/22/the-fedora-20-active-directory-integration-guide-apache-and-nagios). So only users in this group have full access.

Only issue is the nagios cgi access; unfortunately this is comma delimited lists of users, so I wrote a script and put it in cron to run once a weekday to update the cgi user lists.

**Comment by palli** [comment] 2015-08-15 16:39
Clicking between adagios and nagios should break if you are using the same htpasswd defnitions for both (In particular the AuthName is important)

**Comment by palli** [comment] 2015-08-15 16:42
When switching on access_controls, everyone should be able to see the status pages, however they will not see services unless they are defined as contacts for them.

Typically you would achieve this by creating a contactgroup for your user and make sure this contactgroup exists on all your hosts and services.

**Comment by palli** [comment] 2015-08-15 16:43
I wasn't 100% clear from your bug report, but are you still having any problems with this ? 

I am marking this as 'working as intended' for now, but don't hesitate to reopen if you are having any problems.

**Closed by palli** 2015-08-15 16:43 UTC

**Comment by spicysomtam** [comment] 2015-08-15 20:58
Our team is in a particular Active Directory group which is Unix enabled and shows up as Unix group. Thus I wanted all users in this group to have Adagios admin rights. This works with the http authentication based on group, and I have a script that generates the user list to provide nagios CGI access (run from cron daily). That all works fine, and we can add users who are not in the AD group by defining them in nagios host groups file.

I was really wondering if users could be defined to Adagios who could access the GUI but not have admin rights. So they could see status, view logs, etc but not make any config changes/reload nagios/etc. Adagios provides a nice modern interface rather than the Nagios web interface that looks very dated.

**Comment by palli** [comment] 2015-08-17 19:18
Yes, you can. 

Check out https://github.com/opinkerfi/adagios/wiki/Users-guide#access-control for enabling access controls inside adagios (by default if you have access into adagios, you have admin rights). After this the following rules apply:

* Users who are 'administrators' according to /etc/adagios/access.conf can do everything
* Users who are 'operators' can access status related data and acknowledge services, but not change configuration
* Users who are not defined in any group can access the status interface, but they will only see services who they are marked as a contact for in the nagios config files.

**Comment by spicysomtam** [comment] 2015-08-28 10:54
Havn't got round to implementing this yet.

I checked out your link and you might want to update the docs; it has the first line but does not include the info on operators and users not defined to any groups.

**Comment by spicysomtam** [comment] 2015-09-09 16:58
I just got round to testing this out. It does work. I was caught out by having two enable_authorization= lines in the adagios.conf file; I don't know how this happened! Anyway, when reduced to one it worked.

I also tweaked the /etc/pamd.d/pwauth file to allow multiple groups, and this now works. So we want the UNIX team to have full admin rights, and other teams like Database and Windows to have operator privileges. These three groups have login access to Adagios/Nagios, but the permitted access described further down.

```
# cat /etc/pam.d/pwauth 
#%PAM-1.0
auth       sufficient	pam_succeed_if.so user ingroup [Database Support]
auth       sufficient   pam_succeed_if.so user ingroup [Windows Server Support]
auth       required     pam_succeed_if.so user ingroup [UNIX Server Support]
auth       include      password-auth
account    include      password-auth
```

Adagios apache config file:

```
# cat /etc/httpd/conf.d/adagios.conf 

# Create the wsgi process group
WSGISocketPrefix run/wsgi
WSGIDaemonProcess adagios user=nagios group=nagios processes=1 threads=25
WSGIScriptAlias /adagios /usr/lib/python2.6/site-packages/adagios/wsgi.py

# Run adagios under /adagios
Alias /adagios/media /usr/lib/python2.6/site-packages/adagios/media

<Location /adagios>
   # Everything under /adagios runs in the above process group
   WSGIProcessGroup adagios

   AuthName "Nagios Access"
   AuthType Basic
#   AuthUserFile /etc/nagios/passwd # old setting
   AuthBasicProvider external
   AuthExternal pwauth
   Require valid-user
   # Redirect /adagios to /adagios/
   # So path to css/javascript works
   RedirectMatch ^/adagios$ /adagios/
</Location>
```

Then you need to restrict via user lists in adagios.conf (administrators and operators) and make sure enable_authorization is set to True. The contact groups thing can be setup, but I decided this was another list that would need maintaining, so we don't use this.

Then you need the nagios cgi permissions. I have defined admin access; operator access needs defining/testing.

So I have two scripts running in cron each day that generates the adagios and nagios cgi lists from the linux UNIX group (actually AD); basically means we don't need to do this manually when people leave and join the teams, and these scripts have an exclude list to exclude individuals in the groups (people who have left and they don't want to update the AD lists).

For users who are not in AD and or are not explicitly in these groups, they can just be added to similar groups in the nagios server local /etc/passwd and /etc/group. The script copes with the odd output this creates with getent (combining AD and local group users), and populates the lists accordingly. Let me know if anyone wants these scripts. I will enhance them to generate the operator lists when this is further defined and we have Windows and DBAs clamoring for access!

A nice side effect to all this is since every user logs in as themselves, the Adagios git history shows who did what and all the downtime, etc annotates who did it!
