### ISSUE TITLE
KeyError on Network Parents

### ISSUE THREAD

**Issue by stestaz** [opinkerfi/adagios#661] opened 2019-11-29 14:57 UTC
Hi,
I've an installation with more than 500 hosts, and when 500 hosts is exceeded the Network Parents section explode with this error

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/adagios/status/views.py", line 109, in network_parents
    i['child_hosts'].append(host_dict[x])
KeyError: u'upsCed'

**Comment by stestaz** [comment] 2020-04-03 06:49
Hi, no news about this?

**Comment by palli** [comment] 2020-04-03 10:49
Hey stestaz,

It sounds like one or more of the hosts listed in network_parents don't exist? 

In this case network_parents is referencing a host called 'upsCed' and the host name cannot be found. Be aware that configs errors like this are sometimes silently ignored by nagios itself which may be why you have not noticed up until now.

I think this is all working as intended, so I will will close the issue for now, but please let me know if I missed anything obvious here.

**Closed by palli** 2020-04-03 10:49 UTC

**Comment by stestaz** [comment] 2020-04-03 10:52
> 
> 
> Hey stestaz,
> 
> It sounds like one or more of the hosts listed in network_parents don't exist?
> 
> In this case network_parents is referencing a host called 'upsCed' and the host name cannot be found. Be aware that configs errors like this are sometimes silently ignored by nagios itself which may be why you have not noticed up until now.
> 
> I think this is all working as intended, so I will will close the issue for now, but please let me know if I missed anything obvious here.

Hi, as I wrote at the beginning it is not a parent missing but a bug when there are more than 500 hosts

**Comment by palli** [comment] 2020-04-03 14:32
Curious. This could be adagios.settings.livestatus_limit defaulting to 500. Can you try setting livestatus_limit to a higher value in adagios.conf and see if changes the behavior ?

**Comment by stestaz** [comment] 2020-04-03 14:50
> 
> 
> Curious. This could be adagios.settings.livestatus_limit defaulting to 500. Can you try setting livestatus_limit to a higher value in adagios.conf and see if changes the behavior ?

TOP! now it is working!
thaks so much!
